# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec4a51371952d24ded80617fb365856150a80b7baa3d06666ad59ab01253e2f28ac80c2be52af2c1444ade8d4363f74d9ecaa3d6e1f06c5eb86f8e2c582cc57

test:
  secret_key_base: b95c72123951f6463a8e86a751be70cfac0a869ca79f12f6115b285b7a3cac6f5cf1abc2a7be954653dab380554be42833d1eede3dff3d400e4109ef83b311df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
